name: Sync issues to Jira

'on':
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
  issues:
  issue_comment:
  workflow_run:
    workflows: [jira-issue-sync-review]
    types:
      - completed
concurrency: jira_issues

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_REPOSITORY_OWNER"
      - run: echo "$A_SECRET"
    env:
      A_SECRET: ${{ secrets.A_SECRET }}
  
  sync_issues_to_jira:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "$GITHUB_REPOSITORY_OWNER"
      - run: echo "$A_SECRET"
      - name: Sync GitHub issues to Jira project
        uses: ciscoecosystem/sync-jira-actions@v1
        with:
          sync_label: jira-sync
          status_field_id: 10740
          find_jira_retries: 0
          link_closing_issues: true
          minimum_approvals: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          A_SECRET: ${{ secrets.A_SECRET }}
          JIRA_PROJECT: DCNE
          JIRA_COMPONENT: example-project-repo # TEST
          JIRA_ISSUE_TYPE: GitHub Issue
