name: Manually trigger sync issue to Jira

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to be performed"
        required: true
        default: "mirror-issues"
      issue-numbers:
        description: "Issue numbers"
        required: true
concurrency: jira_issues

jobs:
  sync_issues_to_jira:
    name: Sync issues to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync GitHub issues to Jira project
        uses: espressif/sync-jira-actions@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_PROJECT: DCNE
          JIRA_COMPONENT: ansible-aci # TEST